Client/Controllers/CartController.cs
using Client.Repository.Interface;
using Common.DTO;
using Common.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartRepository _rp;
        private readonly IOrderRepository _rp_order;

        public CartController(ICartRepository rp, IOrderRepository rp_order)
        {
            _rp = rp;
            _rp_order = rp_order;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;
            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            List<ShoppingCart> list = await _rp.GetCarts(Convert.ToInt32(claim.Value));
            IEnumerable<CartVM> listCart = list.Select(c => new CartVM
            {
                Id = c.Id,
                FoodName = c.Food.Name,
                FoodPrice = c.Food.Price,
                Count = c.Count,
                Image = c.Food.Image != null ? $"data:image/jpg;base64,{Convert.ToBase64String(c.Food.Image)}" : "~/img/150.png"
            });
            double total = list.Sum(c => c.Count * c.Food.Price);
            return Json(new { listCart, total });
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int FoodId)
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;
            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim == null)
            {
                return Json(new { success = false, message = "Hãy đăng nhập trước" });
            }
            ShoppingCart cart = new ShoppingCart()
            {
                FoodId = FoodId,
                UserId = Convert.ToInt32(claim.Value)
            };
            if (!await _rp.AddToCart(cart))
            {
                return Json(new { success = false, message = "Thêm thất bại" });
            }
            return Json(new { success = true, message = "Đã thêm vào giỏ" });
        }

        [HttpPost]
        public async Task<IActionResult> PlusCart(int cartId)
        {
            if (!await _rp.PlusCart(cartId))
            {
                return Json(new { success = false, message = "Tăng số lượng thất bại" });
            }
            return Json(new { success = true, message = "Tăng số lượng thành công" });
        }

        [HttpPost]
        public async Task<IActionResult> MinusCart(int cartId)
        {
            if (!await _rp.MinusCart(cartId))
            {
                return Json(new { success = false, message = "Giảm số lượng thất bại" });
            }
            return Json(new { success = true, message = "Giảm số lượng thành công" });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveCart(int cartId)
        {
            if (!await _rp.RemoveCart(cartId))
            {
                return Json(new { success = false, message = "Xoá thất bại" });
            }
            return Json(new { success = true, message = "Xoá thành công" });
        }

        [HttpPost]
        public async Task<IActionResult> PlaceOrder()
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;
            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            int UserId = Convert.ToInt32(claim.Value);
            if (!await _rp_order.PlaceOrder(UserId))
            {
                return Json(new { success = false, message = "Đặt món thất bại" });
            }
            return Json(new { success = true, message = "Thành công đặt món" });
        }
    }
}

Client/Controllers/FoodController.cs
using Client.Repository.Interface;
using Common.Entities;
using Common.Extension;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles = Constant.Role_Admin)]
    public class FoodController : Controller
    {
        private readonly IFoodRepository _rp;
        public FoodController(IFoodRepository rp)
        {
            _rp = rp;
        }

        public async Task<IActionResult> Index()
        {
            List<Food> list = await _rp.GetAllAsync();
            return View(list);
        }


        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            Food food = new Food();
            // Create
            if (id == null)
            {
                return View(food);
            }
            // Edit
            food = await _rp.GetAsync(id.GetValueOrDefault()); //value or null
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Food food)
        {
            if (ModelState.IsValid)
            {
                IFormFileCollection files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] pic = null;
                    using (var fs = files[0].OpenReadStream())
                    {
                        using var ms = new MemoryStream();
                        fs.CopyTo(ms);
                        pic = ms.ToArray();
                    }
                    food.Image = pic;
                }
                else if (food.Id == 0)
                {
                    // If we're creating but not choose any Picture
                    food.Image = null;
                }
                else
                {
                    //Reuse old picture if we're updating and not choose any Picture
                    Food objFromDb = await _rp.GetAsync(food.Id);
                    food.Image = objFromDb.Image;
                }


                if (food.Id == 0)
                {
                    if (!await _rp.CreateAsync(food))
                    {
                        return BadRequest();
                    }
                }
                else
                {
                    if (!await _rp.UpdateAsync(food))
                    {
                        return BadRequest();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            Food obj = await _rp.GetAsync(id);
            if (obj == null || !await _rp.DeleteAsync(id))
            {
                return Json(new { success = false, message = "Xoá thất bại" });
            }
            else
            {
                return Json(new { success = true, message = "Xoá thành công" });
            }
        }
    }
}

Client/Controllers/MenuController.cs
using Client.Repository.Interface;
using Common.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class MenuController : Controller
    {
        private readonly IFoodRepository _rp;
        public MenuController(IFoodRepository rp)
        {
            _rp = rp;
        }

        public async Task<IActionResult> Index()
        {
            List<Food> list = await _rp.GetAllAsync();
            return View(list);
        }
    }
}

Client/Controllers/RequestController.cs
using Client.Repository.Interface;
using Common.DTO;
using Common.Extension;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles = Constant.Role_Customer)]
    public class RequestController : Controller
    {
        private readonly IRequestRepository _rp;
        public RequestController(IRequestRepository rp)
        {
            _rp = rp;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendRequest(string message)
        {
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;
            Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            UserRequest ur = new UserRequest
            {
                UserId = Convert.ToInt32(claim.Value),
                Message = message
            };
            if (!await _rp.SendRequest(ur))
            {
                return Json(new { success = false, message = "Gửi thất bại" });
            }
            return Json(new { success = true, message = "Gửi thành công" });
        }
    }
}

Client/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAcc
@{
    string IsLoggedInStr = httpAcc.HttpContext.Session.GetString("IsLoggedIn");
    bool IsLoggedIn = Convert.ToBoolean(IsLoggedInStr);
    string DisplayName = httpAcc.HttpContext.Session.GetString("DisplayName");
}

<header>
    <a asp-controller="Home" asp-action="Index" class="logo">Luxury Restaurant</a>
    <nav class="navbar">
        <a class=@ViewData["HomeActive"] asp-controller="Home" asp-action="Index">Trang chủ</a>
        <a class=@ViewData["MenuActive"] asp-controller="Menu" asp-action="Index">Menu</a>
        @if (IsLoggedIn && (User.IsInRole(Constant.Role_Admin)))
        {
            <a class=@ViewData["FoodActive"] asp-controller="Food" asp-action="Index">Quản lý</a>
        }
        @if (IsLoggedIn && (User.IsInRole(Constant.Role_Customer)))
        {
            <a class=@ViewData["RequestActive"] asp-controller="Request" asp-action="Index">Yêu cầu</a>
        }
    </nav>


    @if (IsLoggedIn)
    {
        <div class="icons">
            <a style="font-size:20px">@DisplayName</a>
            <a asp-controller="Cart" asp-action="Index" class="fas fa-shopping-cart"></a>
            <a asp-controller="Home" asp-action="Logout" class="fas fa-sign-out-alt"></a>
        </div>
    }
    else
    {
        <div class="icons">
            <a asp-controller="Cart" asp-action="Index" class="fas fa-shopping-cart"></a>
            <a asp-controller="Home" asp-action="Login" class="fas fa-user"> </a>
        </div>
    }
</header>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/dataTable/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>
    @await RenderSectionAsync("MYCSS", required: false)
    <partial name="_Header" />
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/font-awesome/e19c476714.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_PrivateLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    @await RenderSectionAsync("MYCSS", required: false)
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>